# Generated by Django 5.1.5 on 2025-05-02 05:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tealives', '0002_alter_activity_a_id_alter_files_f_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dob', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('user_zone', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_logged_in', models.BooleanField(default=False, verbose_name='Logged In')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False, help_text='Select if user should be verified. ', verbose_name='Verified')),
                ('is_disabled', models.BooleanField(default=False, help_text='Designates whether this users account should be disabled. Select this when user violates policy.', verbose_name='Disabled')),
                ('date_joined', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Date Joined')),
                ('bio', models.TextField(blank=True)),
                ('p_no', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('last_login', models.DateTimeField(auto_now=True, max_length=50, verbose_name='Last Login')),
                ('display_picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tealives.files')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
