# Generated by Django 3.2 on 2022-07-09 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tealives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_text',
            name='chat_from',
            field=models.ForeignKey(default='32f39a15-3c89-4e92-9801-0b9d186ffcb2', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat_text',
            name='chat_to',
            field=models.ForeignKey(default='00ba5c81-7cdc-464e-9f80-1c41cb1d7ef4', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.customuser'),
            preserve_default=False,
        ),
    ]
