# Generated by Django 5.1.5 on 2025-05-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='a_id',
            field=models.CharField(default='b64e61eb-c3c9-43f9-862f-f5bd2a3c6f8d', max_length=225, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='files',
            name='f_id',
            field=models.CharField(default='0b20e26e-955f-48ac-82ee-cd54c901d0d8', max_length=225, unique=True),
        ),
    ]
