# Generated by Django 5.1.5 on 2025-05-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0002_alter_activity_a_id_alter_files_f_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='a_id',
            field=models.CharField(default='f86b6a25-3c41-4d7e-837d-ca93865e03ea', max_length=225, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='files',
            name='f_id',
            field=models.CharField(default='20244d17-e382-4746-b636-d5adf89ffd5f', max_length=225, unique=True),
        ),
    ]
