# Generated by Django 4.1.3 on 2022-12-25 01:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0002_auto_20220708_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat_room',
            old_name='date_created',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='chat_room',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chat_text',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat_text',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
