# Generated by Django 4.1.3 on 2022-12-27 06:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tealives', '0003_rename_date_created_chat_room_created_on_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat_state',
            new_name='Chat_log',
        ),
    ]
