# Generated by Django 5.1.5 on 2025-05-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0003_alter_activity_a_id_alter_files_f_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='a_id',
            field=models.CharField(default='059b065b-cbb2-4904-9d71-70542103d4ad', max_length=225, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='files',
            name='f_id',
            field=models.CharField(default='34c8486b-e653-48d1-bc19-d15525839c09', max_length=225, unique=True),
        ),
    ]
