# Generated by Django 4.1.3 on 2022-12-27 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0004_rename_chat_state_chat_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat_log',
            old_name='user_typing',
            new_name='event_user',
        ),
    ]
