# Generated by Django 5.1.5 on 2025-05-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0004_alter_activity_a_id_alter_files_f_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='a_id',
            field=models.CharField(default='86a24431-447e-4f21-a25a-b78efb412dad', max_length=225, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='files',
            name='f_id',
            field=models.CharField(default='1be67839-5446-4bae-b984-cae0f87f453e', max_length=225, unique=True),
        ),
    ]
