# Generated by Django 4.1.3 on 2022-12-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0005_rename_user_typing_chat_log_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_log',
            name='chat_state',
            field=models.CharField(choices=[('N', 'None'), ('T', 'Story Picture')], default='N', max_length=1),
        ),
    ]
