# Generated by Django 4.1.3 on 2022-12-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0006_alter_chat_log_chat_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_log',
            name='chat_state',
            field=models.CharField(choices=[('N', 'None'), ('T', 'Typing')], default='N', max_length=1),
        ),
    ]
