# Generated by Django 4.1.3 on 2022-12-29 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0007_alter_chat_log_chat_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='chat_log',
            options={'verbose_name_plural': 'Chat Logs'},
        ),
        migrations.AlterModelOptions(
            name='chat_text',
            options={'verbose_name_plural': 'Chat Texts'},
        ),
    ]
