# Generated by Django 4.1.3 on 2023-01-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0008_alter_activity_options_alter_chat_log_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_log',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
