# Generated by Django 4.1.3 on 2023-01-29 20:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0009_alter_chat_log_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='file',
            new_name='fileName',
        ),
        migrations.AddField(
            model_name='follower_followed',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follower_followed',
            name='status',
            field=models.CharField(choices=[('N', 'None'), ('F', 'Following')], default='F', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post_likes',
            name='post',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='tealives.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post_likes',
            name='status',
            field=models.CharField(choices=[('L', 'Liked'), ('U', 'Unliked')], default='L', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follower_followed',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
