# Generated by Django 4.1.3 on 2023-02-05 00:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tealives', '0010_rename_file_story_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_room',
            name='members',
            field=models.ManyToManyField(default='', to=settings.AUTH_USER_MODEL),
        ),
    ]
