# Generated by Django 4.1.3 on 2023-02-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0013_alter_chat_room_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_room',
            name='members',
            field=models.ManyToManyField(default='', to='tealives.chat_member'),
        ),
    ]
