# Generated by Django 4.1.3 on 2023-02-05 03:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0016_alter_chat_room_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_likes',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post_likes',
            name='date_liked',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
