# Generated by Django 4.1.3 on 2023-02-06 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0017_post_likes_date_modified_alter_post_likes_date_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file',
        ),
        migrations.AddField(
            model_name='files',
            name='uploadedFile',
            field=models.FileField(default='', upload_to='uploads/%Y/%m/%d/', verbose_name='file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='template',
            field=models.IntegerField(choices=[(1, 'Template 1'), (2, 'Template 2'), (3, 'Template 3'), (4, 'Template 4')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post_likes',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tealives.post'),
        ),
    ]
