# Generated by Django 4.1.3 on 2023-02-21 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tealives', '0018_remove_files_file_files_uploadedfile_post_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='c_replies',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment_reply',
            name='c_comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tealives.comments'),
        ),
        migrations.AddField(
            model_name='comments',
            name='c_post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tealives.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='c_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
