# Generated by Django 4.1.3 on 2023-02-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0019_remove_comments_c_replies_remove_post_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
