# Generated by Django 4.1.3 on 2023-02-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0020_alter_comments_c_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='c_time',
            new_name='c_modified',
        ),
        migrations.AddField(
            model_name='comments',
            name='c_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
