# Generated by Django 5.1.5 on 2025-04-21 20:07

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0021_rename_c_time_comments_c_modified_comments_c_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='c13863da-ccfc-4b8e-bc8b-9f12caaec472', max_length=100, verbose_name='')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
    ]
