# Generated by Django 5.1.5 on 2025-04-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0022_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='title',
            field=models.CharField(default='69ccee9d-045b-4bd4-9344-7f4e5f70ef8d', max_length=100, verbose_name=''),
        ),
    ]
