# Generated by Django 5.1.5 on 2025-04-26 05:48

import datetime
import tealives.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0023_alter_photos_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photos',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='time',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity',
            field=models.CharField(choices=[('Login', 'Login'), ('Like', 'Post Like'), ('post_c', 'Post Create'), ('story_c', 'Story Create')], default='Login', max_length=50, verbose_name='Activity Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 26, 5, 48, 3, 544558, tzinfo=datetime.timezone.utc), verbose_name='Date Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='a_id',
            field=models.CharField(default='4057dc90-fc59-488c-bd8d-723da4450992', max_length=225, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='files',
            name='f_id',
            field=models.CharField(default='b480b271-d0aa-400b-9211-0bd0746c6ae3', max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='uploadedFile',
            field=models.FileField(upload_to=tealives.models.dynamic_upload_path, verbose_name='file'),
        ),
    ]
