# Generated by Django 5.1.5 on 2025-04-26 06:39

import cloudinary_storage.storage
import tealives.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0024_delete_photos_remove_activity_time_activity_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='a_id',
            field=models.CharField(default='518c95a0-26fa-43c9-ba7b-01369c08ef6c', max_length=225, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='files',
            name='f_id',
            field=models.CharField(default='1e662fef-2b2b-48d1-88ee-4e956003ad03', max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='uploadedFile',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=tealives.models.dynamic_upload_path, verbose_name='file'),
        ),
    ]
