# Generated by Django 5.1.5 on 2025-04-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0025_alter_activity_a_id_alter_files_f_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='a_id',
            field=models.CharField(default='6310b3c4-faa1-4f92-8b88-c58c231abee7', max_length=225, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='files',
            name='f_id',
            field=models.CharField(default='a84f8ec4-6bbf-4f5f-a53f-d699c6cb9044', max_length=225, unique=True),
        ),
    ]
