# Generated by Django 5.1.5 on 2025-04-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0026_alter_activity_a_id_alter_files_f_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='name',
        ),
        migrations.AlterField(
            model_name='activity',
            name='a_id',
            field=models.CharField(default='57a5f5c0-c33c-465e-8dc2-d7e9f531c163', max_length=225, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='files',
            name='f_id',
            field=models.CharField(default='8f04ff18-2618-4692-8cb4-bc05cf918b74', max_length=225, unique=True),
        ),
    ]
