# Generated by Django 5.1.5 on 2025-05-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0027_remove_files_name_alter_activity_a_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='a_id',
            field=models.CharField(default='a7ff2e3d-3779-496b-935d-763531c7b5e3', max_length=225, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='files',
            name='f_id',
            field=models.CharField(default='dfc902c0-0db9-41c7-b1e1-62e52666f862', max_length=225, unique=True),
        ),
    ]
