# Generated by Django 3.2 on 2021-04-30 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0007_auto_20210430_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
