# Generated by Django 3.2 on 2021-04-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0008_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
