# Generated by Django 3.2 on 2021-04-30 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0010_auto_20210430_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
