# Generated by Django 3.2 on 2021-04-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0011_remove_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_disabled',
            field=models.BooleanField(default=False, help_text='Designates whether this users account should be disabled. Unselect this when user violates policy.', verbose_name='disabled'),
        ),
    ]
