# Generated by Django 3.2 on 2021-04-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0012_alter_user_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
