# Generated by Django 3.2 on 2021-04-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0013_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.IntegerField(default='0'),
        ),
    ]
