# Generated by Django 3.2 on 2021-08-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0015_auto_20210430_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Select if user should be verified. ', verbose_name='verified'),
        ),
    ]
