# Generated by Django 3.2 on 2021-08-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0016_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
