# Generated by Django 3.2 on 2021-08-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0017_alter_user_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_modified',
        ),
    ]
