# Generated by Django 3.2 on 2021-08-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0018_remove_user_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
