# Generated by Django 3.2 on 2021-08-23 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0019_user_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255)),
                ('file', models.CharField(max_length=255)),
                ('likes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('comment_text', models.CharField(max_length=255)),
                ('is_disabled', models.BooleanField(default=False, help_text='Designates whether this users account should be disabled. Unselect this when user violates community guidelines.', verbose_name='disabled')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this users post was deleted.', verbose_name='disabled')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='tealives.user')),
                ('tagged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tealives.user')),
            ],
        ),
    ]
