# Generated by Django 3.2 on 2021-08-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0020_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this users post is deleted.', verbose_name='disabled'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_disabled',
            field=models.BooleanField(default=False, help_text='Designates whether this users account should be disabled. Select this when user violates policy.', verbose_name='disabled'),
        ),
    ]
