# Generated by Django 3.2 on 2021-08-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0022_auto_20210823_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(verbose_name='Date Of Birth'),
        ),
    ]
