# Generated by Django 3.2 on 2021-08-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0023_auto_20210823_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(),
        ),
    ]
