# Generated by Django 3.2 on 2021-08-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0024_alter_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
