# Generated by Django 3.2 on 2021-08-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0025_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
    ]
