# Generated by Django 5.1.5 on 2025-05-02 05:38

import cloudinary_storage.storage
import django.db.models.deletion
import tealives.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.CharField(default='a1632ce8-cc17-40ca-b797-dcaabc1d4418', max_length=225, unique=True)),
                ('base', models.CharField(choices=[('U', 'User Picture'), ('S', 'Story Picture'), ('P', 'Post Picture')], max_length=20)),
                ('uploadedFile', models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=tealives.models.dynamic_upload_path, verbose_name='file')),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('file_mime', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_id', models.CharField(default='08c5fde7-8d98-4c79-8127-4bf25be61e83', max_length=225, verbose_name='id')),
                ('date', models.DateTimeField(verbose_name='Date Time')),
                ('location', models.CharField(max_length=255)),
                ('activity', models.CharField(choices=[('Login', 'Login'), ('Like', 'Post Like'), ('post_c', 'Post Create'), ('story_c', 'Story Create')], max_length=50, verbose_name='Activity Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Chat_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat_room',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_state', models.CharField(choices=[('N', 'None'), ('T', 'Typing')], default='N', max_length=1)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('event_user', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tealives.chat_room')),
            ],
            options={
                'verbose_name_plural': 'Chat Logs',
            },
        ),
        migrations.CreateModel(
            name='Chat_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=225)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('chat_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('chat_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tealives.chat_room')),
            ],
            options={
                'verbose_name_plural': 'Chat Texts',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_comment_text', models.CharField(max_length=255)),
                ('c_created', models.DateTimeField(auto_now=True)),
                ('c_modified', models.DateTimeField(auto_now_add=True)),
                ('c_is_deleted', models.BooleanField(default=False)),
                ('c_likes', models.IntegerField(default=0)),
                ('c_receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('c_sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_comment_text', models.CharField(max_length=255)),
                ('r_time', models.DateTimeField()),
                ('r_is_deleted', models.BooleanField(default=False)),
                ('r_likes', models.IntegerField()),
                ('r_reply', models.CharField(max_length=255)),
                ('r_receiver', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('r_sender', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('c_comment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tealives.comments')),
            ],
        ),
        migrations.CreateModel(
            name='Follower_followed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('N', 'None'), ('F', 'Following')], max_length=15)),
                ('date', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('followed', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='followed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Logged_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('time_active', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('p_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, max_length=255)),
                ('title', models.SlugField(blank=True, max_length=100)),
                ('top_text', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
                ('template', models.IntegerField(choices=[(1, 'Template 1'), (2, 'Template 2'), (3, 'Template 3'), (4, 'Template 4')])),
                ('is_disabled', models.BooleanField(default=False, help_text='Designates whether this users post should be disabled. Select this when post violates community guidelines.', verbose_name='disabled')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this post is deleted.', verbose_name='deleted')),
                ('last_modified', models.DateTimeField(auto_now_add=True, verbose_name='last modified')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('files', models.ManyToManyField(to='tealives.files')),
                ('tagged', models.ManyToManyField(blank=True, related_name='Username', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='c_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tealives.post'),
        ),
        migrations.CreateModel(
            name='Post_likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('L', 'Liked'), ('U', 'Unliked')], max_length=15)),
                ('date_liked', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tealives.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_type', models.BooleanField(default=0)),
                ('two_ver', models.BooleanField(default=0)),
                ('sec_answer', models.CharField(choices=[('MN', 'What is your middle name?'), ('FF', 'What is your favourite food?'), ('FW', 'What is your favourite day of the week?'), ('FN', 'What is your first Nickname?'), ('PN', "What is your pet's name?")], default='', max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=225)),
                ('story_id', models.CharField(max_length=255)),
                ('text', models.CharField(blank=True, max_length=255)),
                ('fileName', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tealives.files')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_verified', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
