# Generated by Django 5.1.5 on 2025-05-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='a_id',
            field=models.CharField(default='a4120a80-1d60-4793-8c8e-a84fdecdab43', max_length=225, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='files',
            name='f_id',
            field=models.CharField(default='bf59046a-75b7-4c63-abf3-ae68e6f82c5c', max_length=225, unique=True),
        ),
    ]
