# Generated by Django 3.2 on 2021-10-30 19:19

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0002_initial'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='comment_reply',
            name='r_comment_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='comment_reply',
            name='r_reply',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tealives.user')),
            ],
        ),
        migrations.CreateModel(
            name='Follower_followed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='tealives.user')),
                ('follower', models.ManyToManyField(related_name='followed', to='tealives.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_comment_text', models.CharField(max_length=255)),
                ('c_time', models.DateTimeField()),
                ('c_is_deleted', models.BooleanField(default=False)),
                ('c_likes', models.IntegerField()),
                ('c_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tealives.post')),
                ('c_receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tealives.user')),
                ('c_replies', models.ManyToManyField(to='tealives.Comment_reply')),
                ('c_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tealives.user')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('user', models.ManyToManyField(to='tealives.User')),
            ],
        ),
        migrations.AddField(
            model_name='comment_reply',
            name='r_receiver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tealives.user'),
        ),
        migrations.AddField(
            model_name='comment_reply',
            name='r_sender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tealives.user'),
        ),
    ]
