# Generated by Django 3.2 on 2021-10-30 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0003_auto_20211030_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_reply',
            name='r_comment_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comment_reply',
            name='r_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tealives.user'),
        ),
        migrations.AlterField(
            model_name='comment_reply',
            name='r_reply',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comment_reply',
            name='r_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tealives.user'),
        ),
    ]
