# Generated by Django 3.2 on 2021-10-30 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0004_auto_20211030_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file0',
        ),
    ]
