# Generated by Django 3.2 on 2021-10-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0005_remove_post_file0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='desc',
        ),
        migrations.AddField(
            model_name='user',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
