# Generated by Django 3.2 on 2021-10-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0006_auto_20211030_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default=''),
        ),
    ]
