# Generated by Django 3.2 on 2021-10-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0007_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(),
        ),
    ]
