# Generated by Django 3.2 on 2021-10-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0008_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(verbose_name='last login'),
        ),
    ]
