# Generated by Django 3.2 on 2021-10-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0009_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
    ]
