# Generated by Django 3.2 on 2021-10-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealives', '0012_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default='2006-12-13'),
        ),
    ]
